### ISSUE TITLE
Support Ctrl+X for cut

### ISSUE THREAD

**Issue by randomascii** [chromium/vs-chromium#22]
I sometimes move a search term from the "Search Code" field to the "File Paths" field and I automatically try to do this with Ctrl+X/tab/Ctrl+V. But this doesn't work. I eventually remember that I have to do Ctrl+C/Del/tab/Ctrl+V. It would be nice to support Ctrl+X as well.

Not a big deal, just a nice-to-have.

**Comment by rpaquay** [comment]
Hmm... I am confused. Ctrl-X seems to work in both "Search Code" and "File Paths" (as long as the text is selected of course). So, Ctrl-X/tab/Ctrl-V works for me.

**Comment by randomascii** [comment]
It works for me now. I don't know why it didn't before. Closing.

**Comment by randomascii** [comment]
It stopped working again. It's odd that just this one shortcut misbehaves. It must be a VS peculiarity. I assume that restarting VS will fix it.

**Comment by rpaquay** [comment]
Weird... It this VS 2015?

**Comment by randomascii** [comment]
Yes. It works fine otherwise. That may well be the difference because I didn't notice it with VS 2013. Then again, I've been using VS 2015 for a month or so and only noticed it last week.
