### ISSUE TITLE
VsChromium should/could warn when search settings prevent finding anything

### ISSUE THREAD

**Issue by randomascii** [chromium/vs-chromium#23]
Years ago when I wrote a text editor it's search functionality had a special behavior for when no match was found. If "whole words" or "case-sensitive" was enabled then it would automatically repeat the search with these settings disabled and, if something was found, it would tell the user. Something like:

"No instances of 'fooBAr' found because case sensitivity was enabled.

It was unobtrusive and easy to ignore, but sometimes it would be brilliant. Every now and then I am unable to find results because I have forgotten to uncheck one of those filters.

Alternate implementations could involve always displaying how many hits there would be if there was no filtering, or displaying it any time that the number of results is less than some threshold (a hundred?). There are some human factors details that can make this slightly better or worse. But, it's fairly easy to get this so it provides some subtle additional information without ever _demanding_ the user's attention.

**Comment by rpaquay** [comment]
Agree this would be useful. Easiest would be to run a 2nd search if either whole words/case sensitive is enabled, and display somewhere (all the time) the number of hits the 2nd search returned. As long as the 2nd search is run asynchronously, it should not affect responsiveness for the user.

I probably need .5 day to implement this.

**Comment by rpaquay** [comment]
Fixed in https://github.com/chromium/vs-chromium/releases/tag/v0.9.20

**Comment by randomascii** [comment]
Nice! I love it.
