### ISSUE TITLE
Better scanning settings

### ISSUE THREAD

**Issue by andresiraola** [chromium/vs-chromium#24]
It would be nice to be able to configure how I'd like the extension to scan my solution.

Right now it scans it everytime I open Visual Studio and 200k files in a HDD could take a while. I would like to control when I want to scan the solution or update my index.

Also, there is no way to stop the scanning. I have to kill the scanning server but I cannot relaunch the scanning without restarting visual studio.

**Comment by rpaquay** [comment]
This sounds like a reasonable request. Would a "pause" button in the Code Search toolbar work (next to the "Refresh" button)?

**Comment by rpaquay** [comment]
This is fixed in version [0.9.28](https://github.com/chromium/vs-chromium/releases/tag/v0.9.28):  There is a "Pause" button in the Code Search tool window.
