### ISSUE TITLE
VsChromium should visually indicate when it hits the maximum # of results

### ISSUE THREAD

**Issue by randomascii** [chromium/vs-chromium#25]
I just tried searching for "v8" (including the quotes) in one of my repos using VsChromium. The results vary from time to time. If I repeatedly paste in the string then the results keep changing.

It looks like VsChromium stops after the first 10,000 results, and the multi-threaded nature of the search means that the first 10,000 results are different every time, but there is not a great indication that the search was aborted.

I've hit variations on this issue a couple of times. It's not a bug, but some sort of indication that the results are partial would make it more obvious that the search should be constrained more heavily, or Tools-> Options should be used to increase the maximum number of results.

**Comment by rpaquay** [comment]
There is a Tools | Options page to change these values:

![image](https://cloud.githubusercontent.com/assets/1087507/20365585/3ff93952-abfc-11e6-87f1-62125b434114.png)

I agree it would be nice to have an indicator.

**Comment by rpaquay** [comment]
Oh nevermind, you found the options page, you are requesting that there is an indicator to go change the options, correct?

**Comment by randomascii** [comment]
A visual indicator, yes. Although I think that in most cases my response would not be to change the maximum but to filter the results more. It could say something like:

"Maximum number of results hit - some results omitted. Use Tools-> Options to increase the limit, or change your query to exclude more results."

Outlook has a warning like this if you do a search query that returns too many results.

**Comment by rpaquay** [comment]
Fixed in a21a076e30960c79e77a5d424bad19d9f44c5f4a
