### ISSUE TITLE
file in GBK encoded line jump to wrong place

### ISSUE THREAD

**Issue by gggin** [chromium/vs-chromium#27]
if GBK encoded,
find then click position in codes
it jump wrong position

**Comment by rpaquay** [comment]
Note: This happens with all variable byte length encoding (e.g. utf8). The issue is that VSChromium treats byte offsets the same as character offsets for all encoding types except UTF-16.

**Comment by gggin** [comment]
I understand the reason... will you fix this?

**Comment by rpaquay** [comment]
Yes. I made a (partial) fix in https://github.com/chromium/vs-chromium/commit/c713abfe8630862d909a595f1e295ebb24498574

**Comment by gggin** [comment]
thank you

**Comment by rpaquay** [comment]
Fixed in https://github.com/chromium/vs-chromium/releases/tag/v0.9.20
