### ISSUE TITLE
VsChromium needs updating for VS 2019

### ISSUE THREAD

**Issue by randomascii** [chromium/vs-chromium#49]
VsChromium works with VS 2019 Preview - for now. However it will stop working in the future. Details can be found here:

https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

I followed the instructions and found this entry in the activity log:

  <entry>
    <record>618</record>
    <time>2018/12/07 18:34:22.913</time>
    <type>Warning</type>
    <source>SyncAutoLoadedExtensions</source>
    <description>Extension &apos;VsChromium&apos; uses the &apos;synchronous auto-load&apos; feature of Visual Studio. This feature will no longer be supported in a future Visual Studio 2019 update, at which point this extension will not work. Please contact the extension vendor to get an update. (UI Context: {f1536ef8-92ec-443c-9ed7-fdadf150da82} Package Guid: {a10cf7af-5f0a-4502-b44b-51ff1b7c8a87})</description>
  </entry>

**Comment by rpaquay** [comment]
There is a pre-release addressing this issue: https://github.com/chromium/vs-chromium/releases/tag/v0.9.31

**Comment by randomascii** [comment]
Installed and testing - working well so far

**Comment by rpaquay** [comment]
As mentioned in the release notes, this pre-release has a regression with displaying icons for known file types. Instead of displaying icons specific to known file types (e.g. C, C++, C#, etc), we display a single generic "text file" icon. This is because an undocumented API has disappeared, and it is unclear what to use instead.

**Comment by randomascii** [comment]
I never noticed the icons. I guess I'm noticing them now but when I check on 0.9.30 - still installed on a different machine - I see the same generic text icons.

In both cases I am using VS 2019. I tested with VS 2017 (also 0.9.30) and I still see generic text icons in the search results. So, I'm not sure when this last worked, but it is not a regression that bothers me personally.

**Comment by rpaquay** [comment]
Fixed in https://github.com/chromium/vs-chromium/releases/tag/v0.9.31.
