### ISSUE TITLE
VsChromium fails for some users on VS 2019 16.1.0

### ISSUE THREAD

**Issue by randomascii** [chromium/vs-chromium#52]
VsChromium on VS 2019 16.1.0 works for me but a developer on chromium-dev finds that it does not:

I just did the update to 16.1.0, and now the VsChromium extension no longer works "because it uses deprecated synchronous autoload APIs."

https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/KM_FtdPGc_I/TjtEmq_5AgAJ

Even though this doesn't reproduce for me the report is consistent with the extensions direction that Visual Studio is moving in and seems worth investigating.

**Comment by awscreen** [comment]
After uninstalling and then reinstalling the VsChromium extension it is functioning again (as described by another developer on chromium-dev in the thread above).  Visual Studio still provides a warning that it didn't load an extension, and opening the Performance Manager dialog shows VsChromium is what it is notifying about.

**Comment by rpaquay** [comment]
There is a pre-release addressing this issue: https://github.com/chromium/vs-chromium/releases/tag/v0.9.31

**Comment by rpaquay** [comment]
Fixed in https://github.com/chromium/vs-chromium/releases/tag/v0.9.31.
